In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [4]:
from google.colab import files
import io
uploded = files.upload()
data = pd.read_csv(io.BytesIO(uploded['bbc-text (2).csv']))
data = data[:100000]
data.head()

Saving bbc-text.csv to bbc-text (2).csv


category                                               text
0           tech  tv future in the hands of viewers with home th...
1       business  worldcom boss  left books alone  former worldc...
2          sport  tigers wary of farrell  gamble  leicester say ...
3          sport  yeading face newcastle in fa cup premiership s...
4  entertainment  ocean s twelve raids box office ocean s twelve...

In [5]:
data.isnull().sum()


category    0
text        0
dtype: int64

In [6]:
data = data.fillna(method='ffill')

In [7]:
data['category'].nunique(), data.text.nunique()

(5, 2126)

In [8]:
data.head()

category                                               text
0           tech  tv future in the hands of viewers with home th...
1       business  worldcom boss  left books alone  former worldc...
2          sport  tigers wary of farrell  gamble  leicester say ...
3          sport  yeading face newcastle in fa cup premiership s...
4  entertainment  ocean s twelve raids box office ocean s twelve...

In [9]:
data.groupby('text').size().reset_index(name='counts')

text  counts
0     $1m payoff for former shell boss shell is to p...       1
1     &#163;1.8m indecency fine for viacom media gia...       1
2     2004: an irish athletics year 2004 won t be re...       1
3     2d metal slug offers retro fun like some drill...       2
4     a decade of good website design the web looks ...       1
...                                                 ...     ...
2121  yukos seeks court action on sale yukos will re...       1
2122  yukos sues four firms for $20bn russian oil fi...       1
2123  yukos unit buyer faces loan claim the owners o...       1
2124  yukos unit fetches $9bn at auction a little-kn...       1
2125  zambia confident and cautious zambia s technic...       1

[2126 rows x 2 columns]

In [10]:
X = data.drop('category', axis=1)
X.head()

text
0  tv future in the hands of viewers with home th...
1  worldcom boss  left books alone  former worldc...
2  tigers wary of farrell  gamble  leicester say ...
3  yeading face newcastle in fa cup premiership s...
4  ocean s twelve raids box office ocean s twelve...

In [11]:
X.columns

Index(['text'], dtype='object')

In [12]:
v = DictVectorizer(sparse=False)
X = v.fit_transform(X.to_dict('records'))
X.shape

(2225, 2126)

In [14]:
y = data.category.values
print(y)

['tech' 'business' 'sport' ... 'entertainment' 'politics' 'sport']


In [15]:
classes = np.unique(y)

In [16]:
classes = classes.tolist()
classes

['business', 'entertainment', 'politics', 'sport', 'tech']

In [17]:
X.shape, y.shape

((2225, 2126), (2225,))

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state=0)
# print("x training : ",X_train)
# print("y training : ",y_train)
# print("x test : ",X_test)
#print("y test : ",y_test)

x test :  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [22]:
X_train.shape, y_train.shape

((1490, 2126), (1490,))

In [26]:
new_classes = classes.copy()
# new_classes.pop()
new_classes

['business', 'entertainment', 'politics', 'sport', 'tech']

In [27]:
per = Perceptron(verbose=10, n_jobs=-1, max_iter=5)
per.partial_fit(X_train, y_train, classes)

-- Epoch 1
-- Epoch 1
Norm: 25.63, NNZs: 639, Bias: -1.000000, T: 1490, Avg. loss: 0.212081
Total training time: 0.01 seconds.
Norm: 22.87, NNZs: 505, Bias: -1.000000, T: 1490, Avg. loss: 0.167114
Total training time: 0.01 seconds.
-- Epoch 1-- Epoch 1

Norm: 24.58, NNZs: 595, Bias: 0.000000, T: 1490, Avg. loss: 0.198658
Total training time: 0.01 seconds.
Norm: 24.02, NNZs: 556, Bias: -1.000000, T: 1490, Avg. loss: 0.183893-- Epoch 1
Total training time: 0.01 seconds.

Norm: 23.43, NNZs: 495, Bias: -1.000000, T: 1490, Avg. loss: 0.159732
Total training time: 0.01 seconds.


[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done   3 out of   5 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    0.0s finished


Perceptron(max_iter=5, n_jobs=-1, verbose=10)

In [28]:
print(classification_report(y_pred=per.predict(X_test), y_true=y_test, labels=new_classes))

               precision    recall  f1-score   support

     business       1.00      0.01      0.01       168
entertainment       1.00      0.07      0.12       123
     politics       1.00      0.02      0.05       124
        sport       0.26      1.00      0.42       190
         tech       1.00      0.04      0.07       130

     accuracy                           0.28       735
    macro avg       0.85      0.23      0.13       735
 weighted avg       0.81      0.28      0.15       735

